[tool.poetry]
name = "Battlesnake"
version = "1.0.0"
description = "My Battlesnake written in Python"
authors = ["Mandeep Dalavi <mandeepdalavi@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"
cherrypy = "^18.6"
